import argparse
import importlib.util
import pprint
import time
from pathlib import Path
from statistics import mean

import torch
from diffusers import FluxPipeline
from diffusers.models.controlnets.controlnet_flux import FluxControlNetModel
from diffusers.pipelines.flux.pipeline_flux_controlnet import FluxControlNetPipeline
from diffusers.utils import load_image


BASE_MODEL = "./models/FLUX.1-schnell"
CONTROLNET_MODEL = "./models/Xlabs-AI--flux-controlnet-canny-diffusers"
CONTROL_IMAGE = "./imgs/flux_canny_image.png"
OUTPUT_FILE = Path(__file__).with_name("workflow_timeouts.py")

TXT2IMG_WORKFLOW = "flux_schnell_txt2img_cfg_workflow"
CANNY_WORKFLOW = "flux_schnell_txt2img_controlnet_canny_cfg_workflow"

TXT2IMG_PROMPT = "A cat holding a sign that says hello world"
CANNY_PROMPT = (
    "A portrait of a lovely shorthair golden-shaded cat, sitting on a windowsill, "
    "capturing every fur detail."
)


def sync_cuda():
    if torch.cuda.is_available():
        torch.cuda.synchronize()


def measure_request(request_fn, num_requests):
    latencies = []

    for idx in range(num_requests):
        sync_cuda()
        start_time = time.perf_counter()
        request_fn()
        sync_cuda()

        latency = time.perf_counter() - start_time
        latencies.append(latency)
        print(f"  request {idx + 1}: {latency:.4f}s")

    return mean(latencies)


def make_txt2img_request(pipe):
    return lambda: pipe(
        TXT2IMG_PROMPT,
        negative_prompt="ugly, blurry, low quality, deformed, text",
        guidance_scale=0.0,
        num_inference_steps=4,
        max_sequence_length=512,
        generator=torch.Generator("cpu").manual_seed(0),
        true_cfg_scale=7.0,
    ).images[0]


def make_canny_request(pipe, control_image):
    return lambda: pipe(
        CANNY_PROMPT,
        control_image=control_image,
        negative_prompt="NSFW, nude, naked, porn, ugly",
        true_cfg_scale=7.0,
        controlnet_conditioning_scale=0.7,
        guidance_scale=3.5,
        height=1024,
        width=1024,
        num_inference_steps=4,
        max_sequence_length=512,
        generator=torch.Generator("cpu").manual_seed(0),
    ).images[0]


def warmup(request_fn, num_warmups):
    for idx in range(num_warmups):
        print(f"  warmup {idx + 1}")
        request_fn()
        sync_cuda()


def load_existing_timeout_values(output_file):
    if not output_file.exists():
        return {}

    spec = importlib.util.spec_from_file_location("workflow_timeouts", output_file)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return dict(getattr(module, "DEFAULT_WORKFLOW_TIMEOUTS", {}))


def write_timeout_file(measured_timeout_values, output_file):
    timeout_values = load_existing_timeout_values(output_file)
    timeout_values.update(measured_timeout_values)

    content = (
        "# Default timeout values for each workflow (in seconds).\n"
        "# Generated by measure_flux_schnell_workflow_timeouts.py.\n"
        "DEFAULT_WORKFLOW_TIMEOUTS = "
        + pprint.pformat(timeout_values, sort_dicts=True)
        + "\n"
    )
    output_file.write_text(content, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(
        description="Measure mean Flux schnell request latency and write workflow_timeouts.py."
    )
    parser.add_argument("--num-requests", type=int, default=5)
    parser.add_argument("--num-warmups", type=int, default=1)
    parser.add_argument("--output-file", type=Path, default=OUTPUT_FILE)
    args = parser.parse_args()

    timeout_values = {}

    print(f"Loading txt2img pipeline from {BASE_MODEL}")
    txt2img_pipe = FluxPipeline.from_pretrained(BASE_MODEL, torch_dtype=torch.bfloat16)
    txt2img_pipe = txt2img_pipe.to("cuda")
    txt2img_request = make_txt2img_request(txt2img_pipe)

    print(f"Measuring {TXT2IMG_WORKFLOW}")
    warmup(txt2img_request, args.num_warmups)
    timeout_values[TXT2IMG_WORKFLOW] = round(
        measure_request(txt2img_request, args.num_requests), 4
    )
    del txt2img_pipe
    torch.cuda.empty_cache()

    print(f"Loading canny ControlNet pipeline from {BASE_MODEL}")
    controlnet = FluxControlNetModel.from_pretrained(
        CONTROLNET_MODEL,
        torch_dtype=torch.bfloat16,
        use_safetensors=True,
    )
    canny_pipe = FluxControlNetPipeline.from_pretrained(
        BASE_MODEL,
        controlnet=controlnet,
        torch_dtype=torch.bfloat16,
    )
    canny_pipe.to("cuda")
    control_image = load_image(CONTROL_IMAGE)
    canny_request = make_canny_request(canny_pipe, control_image)

    print(f"Measuring {CANNY_WORKFLOW}")
    warmup(canny_request, args.num_warmups)
    timeout_values[CANNY_WORKFLOW] = round(
        measure_request(canny_request, args.num_requests), 4
    )

    write_timeout_file(timeout_values, args.output_file)
    print(f"Wrote timeout values to {args.output_file}")
    print(timeout_values)


if __name__ == "__main__":
    main()
