# Default timeout values for each workflow (in seconds).
# Generated by measure_flux_schnell_workflow_timeouts.py.
DEFAULT_WORKFLOW_TIMEOUTS = {'flux_schnell_txt2img_cfg_workflow': 1.9871,
 'flux_schnell_txt2img_controlnet_canny_cfg_workflow': 2.0688,
 'flux_schnell_txt2img_controlnet_depth_cfg_workflow': 2.4}
